# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'Windows-latest'
  

  #name: 'Default'
#
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  AZP_BASHV3_OLD_SOURCE_BEHAVIOR: true

steps:
#azureCommonVirtualFile: 'openjdk/11.0.3_7/jdk-11.0.7_linux-x64_bin.tar.gz'
#- task: JavaToolInstallerm@0
#  inputs:
#    versionSpec: '11'
#    jdkArchitectureOption: 'x64'
#    jdkSourceOption: 'AzureStorage'
#    azureResourceManagerEndpoint: 'Visual Studio Premium with MSDN(2873a62a-d3fa-40d1-9ba7-188b36586f4f)'
#    azureStorageAccountName: 'abttstorage'
#    azureContainerName: 'testcontainer'
#    azureCommonVirtualFile: 'openjdk/11.0.3_7/jdk-11.0.7_linux-x64_bin.tar.gz'
#    jdkDestinationDirectory: './openjdk'
#    cleanDestinationDirectory: true


- task: DownloadSecureFile@1
  inputs:
    secureFile: 'script.sh'

#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'stat /home/vsts/work/_temp/script.sh'

#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'chmod 444 ''/home/vsts/work/_temp/script.sh'''

- bash: |
    working_dir=$(echo "$(System.DefaultWorkingDirectory")|
    echo "working_dir"











